var $jscomp={scope:{},findInternal:function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var g=a[e];if(c.call(b,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var b=0,d={next:function(){if(b<a.length){var e=b++;return{value:c(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,b){var d=$jscomp.checkStringArgs(this,a,"startsWith");a+="";for(var c=d.length,g=a.length,l=Math.max(0,Math.min(b|0,d.length)),f=0;f<g&&l<c;)if(d[l++]!=a[f++])return!1;return f>=g}},"es6-impl","es3");Number.prototype.clamp=function(a,c){return Math.min(Math.max(this,a),c)};Number.prototype.map=function(a,c,b,d){return this>c?d:d<b?((this-a)*(d-b)/(c-a)+b).clamp(d,b):((this-a)*(d-b)/(c-a)+b).clamp(b,d)};
var TimeSmash={};
(function(){TimeSmash.msPerMinute=6E4;TimeSmash.msPerHour=60*TimeSmash.msPerMinute;TimeSmash.msPerDay=24*TimeSmash.msPerHour;TimeSmash.msPerMonth=30*TimeSmash.msPerDay;TimeSmash.msPerYear=365*TimeSmash.msPerDay;TimeSmash.timeDifference=function(a){a=moment()-a;return a>10*TimeSmash.msPerYear?"Never":a<TimeSmash.msPerMinute?Math.round(a/1E3)+" seconds ago":a<TimeSmash.msPerHour?Math.round(a/TimeSmash.msPerMinute)+" minutes ago":a<TimeSmash.msPerDay?Math.round(a/TimeSmash.msPerHour)+" hours ago":a<
TimeSmash.msPerMonth?"~"+Math.round(a/TimeSmash.msPerDay)+" days ago":a<TimeSmash.msPerYear?"~"+Math.round(a/TimeSmash.msPerMonth)+" months ago":"~"+Math.round(a/TimeSmash.msPerYear)+" years ago"};TimeSmash.timeToAlert=function(a,c){var b=moment()-a;return b/1E3<c?"alert-success":b/1E3<2*c?"alert-info":b/1E3<8*c?"alert-warning":"alert-danger"};TimeSmash.timeToColor=function(a){a=moment()-a;var c=180,b=180,d=180;if(2>a/TimeSmash.msPerMinute)return"rgb(200,255,200)";2<a/TimeSmash.msPerMinute&&1>a/TimeSmash.msPerHour?
(c=a.map(2*TimeSmash.msPerMinute,TimeSmash.msPerHour,200,210),b=a.map(2*TimeSmash.msPerMinute,TimeSmash.msPerHour,255,230),d=a.map(2*TimeSmash.msPerMinute,TimeSmash.msPerHour,200,255)):1<a/TimeSmash.msPerHour&&3>a/TimeSmash.msPerHour?(c=210,b=230,d=255):3<a/TimeSmash.msPerHour&&12>a/TimeSmash.msPerHour?(c=a.map(2*TimeSmash.msPerMinute,12*TimeSmash.msPerHour,210,255),b=a.map(2*TimeSmash.msPerMinute,12*TimeSmash.msPerHour,230,130),d=a.map(2*TimeSmash.msPerMinute,12*TimeSmash.msPerHour,255,120)):12<
a*TimeSmash.msPerHour&&7>a*TimeSmash.msPerDay&&(c=a.map(2*TimeSmash.msPerMinute,24*TimeSmash.msPerHour,255,180),b=a.map(2*TimeSmash.msPerMinute,TimeSmash.msPerHour,130,180),d=a.map(2*TimeSmash.msPerMinute,TimeSmash.msPerHour,120,180));return"rgb("+Math.round(c)+","+Math.round(b)+","+Math.round(d)+")"};TimeSmash.timeToExpiry=function(a){var c=moment();a-=c;if(Math.abs(a)<TimeSmash.msPerMinute)return a=Math.round(a/1E3),0<a?Math.abs(a)+" seconds left":Math.abs(a)+" seconds ago";if(Math.abs(a)<TimeSmash.msPerHour)return a=
Math.round(a/TimeSmash.msPerMinute),0<a?Math.abs(a)+" minutes left":Math.abs(a)+" minutes ago";if(Math.abs(a)<TimeSmash.msPerDay)return a=Math.round(a/TimeSmash.msPerHour),0<a?Math.abs(a)+" hours left":Math.abs(a)+" hours ago";if(Math.abs(a)<TimeSmash.msPerMonth)return a=Math.round(a/TimeSmash.msPerDay),0<a?Math.abs(a)+" days left":Math.abs(a)+" days ago";if(Math.abs(a)<TimeSmash.msPerYear)return a=Math.round(a/TimeSmash.msPerMonth),0<a?Math.abs(a)+" months left":Math.abs(a)+" months ago";a=Math.round(a/
TimeSmash.msPerYear);return 0<a?Math.abs(a)+" years left":Math.abs(a)+" years ago"}})();function slide(a){$("."+a).slideToggle("fast")}function assemble_and_redirect(a){var c=[];$("input:checkbox[name='object-panel-selection']:checked").each(function(){c.push($(this).val())});if(0==c.length)bootbox.alert({title:"No selection!",message:"You must select something!"});else{a="/timestreams/"+a+"/by-id/";for(var b=0;b<c.length;b++)0==b?a+=c[b]:a+="+"+c[b];window.location.href=a}}
(function(){function a(a,b){var d=[],c=this.options;c.onProgress&&a&&c.onProgress.call(this,a,b,this.completed.length-1);this.completed.length+this.errors.length===this.queue.length&&(d.push(this.completed),this.errors.length&&d.push(this.errors),c.onComplete.apply(this,d));return this}var c="addEventListener"in new Image,b=function(a,b){this.options={pipeline:!1,auto:!0,prefetch:!1,cache:!0,onComplete:function(){}};b&&"object"==typeof b&&this.setOptions(b);this.addQueue(a);this.queue.length&&this.options.auto&&
this.processQueue()};b.prototype.setOptions=function(a){var b=this.options,d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return this};b.prototype.addQueue=function(a){this.queue=a.slice();return this};b.prototype.reset=function(){this.completed=[];this.errors=[];return this};b.prototype._addEvents=function(b,e,g){var d=this,f=this.options,h=function(){c?(this.removeEventListener("error",k),this.removeEventListener("abort",k),this.removeEventListener("load",m)):this.onerror=this.onabort=this.onload=
null},k=function(){h.call(this);d.errors.push(e);f.onError&&f.onError.call(d,e,g);a.call(d,e);f.pipeline&&d._loadNext(g)},m=function(){h.call(this);d.completed.push(e);a.call(d,e,this);f.pipeline&&d._loadNext(g)};c?(b.addEventListener("error",k,!1),b.addEventListener("abort",k,!1),b.addEventListener("load",m,!1)):(b.onerror=b.onabort=k,b.onload=m);return this};b.prototype._load=function(a,b){var d=new Image;this._addEvents(d,a,b);var c=this.options.cache?"?cache-bust="+Math.random().toString(36).substring(6):
"";d.src=a+c;return this};b.prototype._loadNext=function(a){a++;this.queue[a]&&this._load(this.queue[a],a);return this};b.prototype.processQueue=function(){var a=0,b=this.queue,c=b.length;this.reset();if(this.options.pipeline)this._load(b[0],0);else for(;a<c;++a)this._load(b[a],a);return this};b.lazyLoad=function(a){a||(a={});for(var c=document.querySelectorAll(a.selector||"img[data-preload]"),d=0,l=c.length,f=[],h;d<l;d++)f.push(c[d].getAttribute("data-preload"));a.onProgress&&(h=a.onProgress);a.onProgress=
function(a,b,d){c[d].src=a;c[d].removeAttribute("data-preload");h&&h.apply(this,arguments)};return f.length?new b(f,a):null};"function"===typeof define&&define.amd?define(function(){return b}):this.preLoader=b}).call(this);var CameraUpdater=function(){var a=this;this.cameras=[];this.rpis=[];this.updateArray();this.updateAllElements();var c=0;d3.timer(function(b){b>c+1E3&&(c=b,a.updateAllElements());return!1},1E3);var b=0;d3.timer(function(c){c>b+3E4&&(b=c,a.updateArray());return!1},1E4)};
CameraUpdater.prototype.updateArray=function(){var a=this;jQuery.getJSON("/api/v3/chambercamera?count=100",function(c){a.cameras=c.resources;a.cameras.forEach(function(a){a.disabled&&a.upload&&a.capture&&(CameraUpdater.disableElement(CameraUpdater.getElementFromId(a.id,"last_uploaded"),a.disableduntil),CameraUpdater.disableText(CameraUpdater.getElementFromId(a.id,"last_uploaded.infobox"),a.disableduntil),CameraUpdater.disableElement(CameraUpdater.getElementFromId(a.id,"last_captured"),a.disableduntil),
CameraUpdater.disableText(CameraUpdater.getElementFromId(a.id,"last_captured.infobox"),a.disableduntil));a.capture||(CameraUpdater.disableElement(CameraUpdater.getElementFromId(a.id,"last_captured")),CameraUpdater.disableText(CameraUpdater.getElementFromId(a.id,"last_captured.infobox")));a.upload||(CameraUpdater.disableElement(CameraUpdater.getElementFromId(a.id,"last_uploaded")),CameraUpdater.disableText(CameraUpdater.getElementFromId(a.id,"last_uploaded.infobox")))})});jQuery.getJSON("/api/v3/raspberrypi?count=100",
function(c){a.rpis=c.resources})};
CameraUpdater.prototype.updateAllElements=function(){this.cameras.forEach(function(a){CameraUpdater.setAlert(CameraUpdater.getElementFromId(a.id,"last_seen"),a.last_seen,60);CameraUpdater.setText(CameraUpdater.getElementFromId(a.id,"last_seen.infobox"),a.last_seen,60);a.disabled||(a.upload&&(CameraUpdater.setAlert(CameraUpdater.getElementFromId(a.id,"last_uploaded"),a.last_uploaded,a.interval),CameraUpdater.setText(CameraUpdater.getElementFromId(a.id,"last_uploaded.infobox"),a.last_uploaded,a.interval)),
a.capture&&(CameraUpdater.setAlert(CameraUpdater.getElementFromId(a.id,"last_captured"),a.last_captured,a.interval),CameraUpdater.setText(CameraUpdater.getElementFromId(a.id,"last_captured.infobox"),a.last_captured,a.interval)))});this.rpis.forEach(function(a){CameraUpdater.setAlert(CameraUpdater.getElementFromId(a.id,"last_seen"),a.last_seen,60);CameraUpdater.setText(CameraUpdater.getElementFromId(a.id,"last_seen"),a.last_seen,60)})};
CameraUpdater.setAlert=function(a,c,b){a.removeClass("alert-success alert-warning alert-danger alert-info alert-disabled").addClass(TimeSmash.timeToAlert(moment(c),2*b))};CameraUpdater.setText=function(a,c,b){a.text(TimeSmash.timeDifference(moment(c)))};CameraUpdater.disableElement=function(a){a.removeClass("alert-success alert-warning alert-danger alert-info alert-disabled").addClass("alert-disabled")};CameraUpdater.disableText=function(a,c){c?a.text("Disabled until "+c):a.text("Disabled")};
CameraUpdater.getElementFromId=function(a,c){return jQuery(".panel-"+a).find("."+c)};Number.prototype.clamp=function(a,c){return Math.min(Math.max(this,a),c)};Number.prototype.map=function(a,c,b,d){return this>c?d:d<b?((this-a)*(d-b)/(c-a)+b).clamp(d,b):((this-a)*(d-b)/(c-a)+b).clamp(b,d)};
$(document).on("click",".ssh",function(a){$.getJSON("/api/raspberry/"+a.target.className.split(" ")[0]+"/id_rsa",function(a){var b="";Object.keys(a.keys).forEach(function(c){b+="<b>"+c+"</b><br>"+a.keys[c]+"<br>"});bootbox.alert(b)})}).on("change",".btn-file :file",function(){var a=$(this),c=a.get(0).files?a.get(0).files.length:1,b=a.val().replace(/\\/g,"/").replace(/.*\//,"");a.trigger("fileselect",[c,b])}).on("fileselect",".btn-file :file",function(a,c,b){$(this).val().split(/[\\\/]/);$(this).parent().removeClass("btn-default").removeClass("btn-danger").addClass("btn-success");
$(this).parent().find(".filename-label").text(b);$("*[for='"+$(this).attr("id")+"']").text(b)}).on("drag dragstart dragend dragover dragenter dragleave drop",".dnd-file-upload",function(a){a.preventDefault();a.stopPropagation()}).on("dragover dragenter",".dnd-file-upload",function(){$(this).addClass("bg-info")}).on("dragleave dragend drop",".dnd-file-upload",function(){$(this).removeClass("bg-info")}).on("drop",".dnd-file-upload",function(a){uploadFile=a.originalEvent.dataTransfer.files[0];a=uploadFile.name.replace(/\\/g,
"/").replace(/.*\//,"");$(this).closest("form").find(".btn-file :file").trigger("fileselect",[1,a])}).on("submit","form.file-upload-form",function(a){a.preventDefault();var c=$(this),b=$(c[0]).find('input[type="file"]');a=new FormData(c[0]);b.val()||(b=b.attr("name"),a.set(b,uploadFile,uploadFile.name));$.ajax({url:c.attr("action"),data:a,cache:!1,dataType:"json",contentType:!1,processData:!1,type:c.attr("method"),error:function(a,b,g){var d=$(c[0]).find(".upload-messages");d.empty();a=JSON.parse(a.responseText);
a.message&&d.append("<span class='label label-warning'>"+a.message+"</span><br>");a.exc&&d.append("<span class='label label-danger'>"+a.exc+"</span><br>");a.errors&&a.errors.forEach(function(a){d.append("<span class='label label-danger'>"+a.field+": "+a.messages.join("\n")+"</span><br>")})},success:function(a,b,g){var d=$(c[0]).find(".upload-messages");d.empty();"undefined"!==typeof a.thumbnail_image&&(b=$("#"+a.id+"-thumbnail-img"),0<b.length?(console.log("Updating thumbnail for "+a.id),b.attr("src",
a.thumbnail_image+"?cachebust="+Math.random()+"?"+Math.random())):(console.log("Adding new thumbnail for "+a.id),b='<a href="#" class="dnd-file-upload thumbnail"><img src="'+a.thumbnail_image+"?cachebust="+Math.random()+'" id="'+a.id+'"-thumbnail-img" class="img-responsive center-block" /></a>',$("#"+a.id+"-table").parent().append(b)));if("undefined"!==typeof a.view)d.append("<span class='label label-success'><a href='"+a.view+"'>"+a.name+"</a></span><br>");else if(a.constructor===Array)a.forEach(function(a){d.append("<span class='label label-success'><a href='"+
a.view+"'>"+a.name+"</a></span><br>")});else if("undefined"!==typeof a.messages)for(b=0;b<a.messages.length;b++)d.append("<span class='label label-"+a.messages[b].status+"'>"+a.messages[b].message+"</span><br>")}})}).on("shown.bs.tab",".nav-tabs a",function(a){var c=window.location.hash.split("?");window.location.hash=1<c.length?a.target.hash+"?"+c.pop():a.target.hash}).on("click",".all-tab-button",function(){$(this).parent().addClass("active");$(".tab-pane").removeClass("active").addClass("active in");
$('[data-toggle="tab"]').parent().removeClass("active")}).on("hover","#progress-whole",function(){$("#progress-label").addClass("hidden");$("#real-progress-label").removeClass("hidden")},function(){$("#real-progress-label").addClass("hidden");$("#progress-label").removeClass("hidden")}).ready(function(){$("tr[class$='-slide'],tr[class*='-slide ']").slideUp(0);var a=document.location.hash;a&&$('.nav-tabs a[href="'+a.split("?")[0]+'"]').tab("show")});
function copyToClipboard(a,c){var b=document.createElement("textarea");b.style.position="fixed";b.style.top=0;b.style.left=0;b.style.width="2em";b.style.height="2em";b.style.padding=0;b.style.border="none";b.style.outline="none";b.style.boxShadow="none";b.style.background="transparent";b.value=a;document.body.appendChild(b);b.select();try{var d=document.execCommand("copy");console.log("Copying text command was "+(d?"successful":"unsuccessful"));d?$("#"+c).removeClass("btn-danger btn-primary").addClass("btn-success"):
$("#"+c).removeClass("btn-success btn-primary").addClass("btn-danger")}catch(e){$("#"+c).removeClass("btn-success btn-primary").addClass("btn-danger")}document.body.removeChild(b);setTimeout(function(){$("#"+c).removeClass("btn-danger btn-success").addClass("btn-primary")},2E3)}function hideunhide(a){a.startsWith(".")||(a="."+a);$(a).toggleClass("hidden")}
function handle4xx(a){a.errors.forEach(function(a){var b=$("#"+a.field+"-help-block"),c=$("#"+a.field);c.parent().parent().parent().addClass("has-error");0<b.length?b.text(a.field+": "+a.message):c.parent().parent().parent().append("<span id='"+a.field+"-help-block' class='help-block'>"+a.messages.join("\n")+"</span>")})}
function decide(a){"undefined"!==typeof a.view&&setTimeout(function(){return window.location=a.view},3E3);a.message&&$(".error-area").append("<div class='alert alert-warning' role='alert'>"+a.message+"</div>");a.exc&&$(".error-area").append("<div class='alert alert-danger' role='alert'>"+a.exc+"</div>");if("undefined"!==typeof a.state){var c=a.uri;switch(a.state){case "SUCCESS":setTimeout(function(){return $.getJSON(c,decide)},500);break;case "FAILURE":a.info.status&&$(".error-area").append("<div class='alert alert-danger' role='alert'>"+
a.info.status+"</div>");a.exc_info&&$(".error-area").append("<div class='alert alert-danger' role='alert'>"+a.exc_info+"</div>");break;case "RETRY":break;case "PENDING":setTimeout(function(){return $.getJSON(c,decide)},1500);break;case "PROGRESS":var b=parseInt(a.info.current/a.info.total*100);$(".progress-bar").text(b+"%").css("width",b+"%").attr("aria-valuenow",b+"%").removeClass("progress-bar-success progress-bar-danger progress-bar-warning progress-bar-default").addClass("progress-bar-info");
$(".progress-label").text(a.info.status).addClass("label-info");setTimeout(function(){return $.getJSON(c,decide)},1E3);break;case "STARTED":setTimeout(function(){return $.getJSON(c,decide)},1E3);break;case null:console.log("Progress handler recieved null status.");setTimeout(function(){return $.getJSON(c,decide)},1E3);break;default:console.log("Progress handler broke, recived "+a.status+" as status")}}}
function submitForm(a){$(".help-block").remove();$(".has-error").removeClass("has-error");$(".error-area").empty();$.ajax({xhr:function(){var a=new window.XMLHttpRequest;$(".progress-whole").removeClass("hidden");$(".progress-label").text("Uploading").addClass("label-info");a.upload.addEventListener("progress",function(a){a.lengthComputable&&(a=parseInt(a.loaded/a.total*100),$(".progress-bar").text(a+"%").css("width",a+"%").attr("aria-valuenow",a+"%").removeClass("progress-bar-success progress-bar-danger progress-bar-warning progress-bar-default").addClass("progress-bar-info"))},
!1);return a},url:$(a).attr("action")+location.search,type:$(a).attr("method"),data:new FormData(a),contentType:!1,cache:!1,processData:!1,timeout:72E5,error:function(a,b,d){b=JSON.parse(a.responseText);b.message&&$(".error-area").append("<div class='alert alert-warning' role='alert'>"+b.message+"</div>");b.exc&&$(".error-area").append("<div class='alert alert-danger' role='alert'>"+b.exc+"</div>");400==a.status&&handle4xx(b)},success:function(c,b,d){$(a).find("button:submit").toggleClass("btn-success",
!0);setTimeout(function(){$(a).find("button:submit").toggleClass("btn-success",!1)},5E3)}}).done(decide)};function ProgressBar(){this._progress=0;this._message="";this.maxOpacity=.6;this.element=document.createElement("div");this.elProgress=document.createElement("div");this.elProgressMessage=document.createElement("div");this.element.innerHTML="";this.element.style.position="fixed";this.element.style.bottom="40px";this.element.style.width="200px";this.element.style.marginLeft="-100px";this.element.style.left="50%";this.element.style.borderRadius="5px";this.element.style.border="1px solid #727678";this.element.style.height=
"16px";this.element.style.padding="1px";this.element.style.textAlign="center";this.element.style.backgroundColor="#6ba8e5";this.element.style.opacity=this.maxOpacity;this.element.style.pointerEvents="none";this.elProgress.innerHTML=" ";this.elProgress.style.backgroundColor="#b8e1fc";this.elProgress.style.position="absolute";this.elProgress.style.borderRadius="5px";this.elProgress.style.width="0%";this.elProgress.style.height="100%";this.elProgress.style.margin="0px";this.elProgress.style.padding=
"0px";this.elProgressMessage.style.position="absolute";this.elProgressMessage.style.width="100%";this.elProgressMessage.innerHTML="loading 1 / 10";document.body.appendChild(this.element);this.element.appendChild(this.elProgress);this.element.appendChild(this.elProgressMessage);this.hide()}ProgressBar.prototype.hide=function(){this.element.style.opacity=0};ProgressBar.prototype.show=function(){this.element.style.opacity=this.maxOpacity};
Object.defineProperty(ProgressBar.prototype,"progress",{get:function(){return this._progress},set:function(a){this._progress=a;this.elProgress.style.width=100*a+"%"}});Object.defineProperty(ProgressBar.prototype,"message",{get:function(){return this._message},set:function(a){this._message=a;this.elProgressMessage.innerHTML=a}});

//# sourceMappingURL=/static/js/dist/custom.cls.js.map